name = "card-trader"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "card-trader-db"
database_id = "c9b3bea1-0a84-41f9-8c90-9400461f39ea"
